### DISCUSSION TITLE
Importance of separate postgres, rabbitmq and redis containers

### DISCUSSION THREAD

**Discussion by talesam** [ONLYOFFICE/Docker-DocumentServer#477] [Q&A] [answered]
In this github there is a docker-compose.yml that I made some modifications on top. I would like to know what is the need for other containers like redis, postgres and rabbitmq, is the performance improvement very big?

```
version: '3.9'

services:
  onlyoffice-documentserver:
    container_name: onlyoffice-documentserver
    image: onlyoffice/documentserver:latest
    depends_on:
      - onlyoffice-postgresql
      - onlyoffice-redis
      - onlyoffice-rabbitmq
    environment:
      - DB_TYPE=postgres
      - DB_HOST=onlyoffice-postgresql
      - DB_PORT=5432
      - DB_NAME=onlyoffice
      - DB_USER=onlyoffice
      - DB_PASSWORD=xxxxx
      - AMQP_URI=amqp://guest:guest@onlyoffice-rabbitmq
      - REDIS_SERVER_HOST=onlyoffice-redis
      - REDIS_SERVER_PORT=6379
      # Uncomment strings below to enable the JSON Web Token validation.
      #- JWT_ENABLED=true
      #- JWT_SECRET=secret
      #- JWT_HEADER=Authorization
      #- JWT_IN_BODY=true
    expose:
      - '80'
      - '443'
    stdin_open: true
    restart: always
    stop_grace_period: 60s
    volumes:
      #- /home/tales/Docker/OnlyOffice/./run-document-server.sh:/app/ds/run-document-server.sh
      #- /home/tales/Docker/OnlyOffice/etc:/etc/onlyoffice
      - /home/tales/Docker/OnlyOffice/data:/var/www/onlyoffice/Data
      - /home/tales/Docker/OnlyOffice/logs:/var/log/onlyoffice
      - /var/lib/onlyoffice/documentserver/App_Data/cache/files
      - /var/www/onlyoffice/documentserver-example/public/files
      - /usr/share/fonts
    networks:
      t4l35-net:

  onlyoffice-redis:
    container_name: onlyoffice-redis
    image: redis
    restart: always
    expose:
      - '6379'
    networks:
      t4l35-net:
  
  onlyoffice-rabbitmq:
    container_name: onlyoffice-rabbitmq
    image: rabbitmq
    restart: always
    expose:
      - '5672'
    networks:
      t4l35-net:

  onlyoffice-postgresql:
    container_name: onlyoffice-postgresql
    image: postgres:9.5
    environment:
      - POSTGRES_DB=onlyoffice
      - POSTGRES_USER=onlyoffice
      - POSTGRES_PASSWORD=xxxxx
      #- POSTGRES_HOST_AUTH_METHOD=trust
    restart: always
    expose:
      - '5432'
    volumes:
      - /home/tales/Docker/OnlyOffice/postgresql_data:/var/lib/postgresql
    networks:
      t4l35-net:

networks:
  t4l35-net:
    name: t4l35-net
    ```
