### DISCUSSION TITLE
Onlyoffice behind reverse proxy won't work (502 Bad Gateway)

### DISCUSSION THREAD

**Discussion by artemis-mike** [ONLYOFFICE/Docker-DocumentServer#711] [Q&A]
**Do you want to request a *feature* or report a *bug*?**
It seems like a bug, but mostly I'd just like some help.

**My setup**
- Ubuntu 18.04.4 LTS (Bionic Beaver) running
- docker version 19.03.5, build 633a0ea838 running several containers
- jwilder/nginx-proxy:0.7.0
- jrcs/letsencrypt-nginx-proxy-companion:v1.12
- nextcloud:18.01
- onlyoffice/documentserver:5.4.2.46
- and some other containers e.g. wordpress, db-servers, ...

**What is the current behavior?**
Except onlyoffice everything works like a charm. I got a sub-domain for every outgoing service (wordpress, nextcloud) handled by nginx-proxy. Now I wanted to add the onlyoffice-documentserver to my nextcloud. 
I added a block to my docker-compose.yml-file stating 
_VIRTUAL_HOST=office.my-domain.tld_
_LETSENCRYPT_HOST=office.my-domain.tld_
When I try to connect to onlyoffice in nextcloud it throws
Server error: `GET https://office.my-domain.tld/healthcheck resulted in a 502 Bad Gateway response: <html> <head><title>502 Bad Gateway</title></head> <body> <center><h1>502 Bad Gateway</h1></center> <hr><center>ngin (truncated...)...`

**What is the expected behavior?**
If I'm using purely the docker-compose-block of the onlyoffice/documentserver:latest omitting certificates and using plain HTTP it works perfectly and shows the beautiful page stating "Thank you for choosing ONLYOFFICE! Document Server is running [...]"
But including it into the reverse-proxy-environment results in that 502-Error.

**DocumentServer Docker tag:**
5.4.2.46

**Host Operating System:**
Ubuntu 18.04.4 LTS (Bionic Beaver) running docker 19.03.5

**Docker-Compose-File Entry**
```
#ONLYOffice
  onyloffice:
    restart: always
    stdin_open: true
    tty: true
    depends_on:
      - nginx-proxy
      - encryption-companion
    image: onlyoffice/documentserver:latest
    volumes:
      - './onlyoffice/var/log/onyloffice:/var/log/onyloffice'
      - './onlyoffice/var/www/onyloffice/data:/var/www/onyloffice/data'
    environment:
      - VIRTUAL_HOST=${ONLYOFFICE_HOST}
      - LETSENCRYPT_HOST=${ONLYOFFICE_HOST}
      - JWT_ENABLE=true
      - JWT_SECRET=${ONLYOFFICE_JWT_SECRET}
      - JWT_HEADER=Authorization
    networks:
      - mynetwork
```

I would prefer to run the documentserver within the single machine hosting everything else over docker. Instead of starting a separate server just for hosting onlyoffice.
