### ISSUE TITLE
Container crash

### ISSUE THREAD

**Issue by SimonDevelop** [ONLYOFFICE/Docker-DocumentServer#103]
Docker container crash after a few seconds of launch (around 40 seconds).
During these few seconds of operation I have the message "Document Server is running" on the 8880 port...

My docker compose :
```yaml
version: '2'

services:

  office:
    image: onlyoffice/documentserver
    restart: always
    volumes:
      - /home/docker/docker-data/office/logs:/var/log/onlyoffice
      - /home/docker/docker-data/office/data:/var/www/onlyoffice/Data
      - /home/docker/docker-data/office/lib:/var/lib/onlyoffice
      - /home/docker/docker-data/office/db:/var/lib/postgresql
    ports:
      - 8880:80
```
