### ISSUE TITLE
nginx going away

### ISSUE THREAD

**Issue by buzz** [ONLYOFFICE/Docker-DocumentServer#105]
After one day or so the nginx inside the container is going away without apparent reason.

`/var/log/onlyoffice/documentserver/nginx.error.log` contains quite a lot of these:
```
2018/05/14 09:46:49 [error] 581#581: *8 no live upstreams while connecting to upstream, client: 172.18.0.9, server: , request: "GET /2018-04-24-11-56/doc/143756_1514446954/c/info?t=1126241506277 HTTP/1.1", upstream: "http://docservice/doc/433736_1115444944/c/info", host: "docservice", referrer: "https://XXX.XXX.XX/2018-04-24-11-56/web-apps/apps/spreadsheeteditor/main/index.html?_dc=2018-04-22-11-56&lang=de&customer=ONLYOFFICE&frameEditorId=iframeEditor
```

Then there is `/var/log/nginx/error.log` that show plenty of this:

```
2018/05/16 07:12:13 [info] 16581#16581: Using 32768KiB of shared memory for push module in /etc/nginx/nginx.conf:63
```

Server has 6GB RAM, 4GB swap, 2 cores, Linux 4.13.11-1-ARCH

Starting it with `docker-compose` and have it behind an nginx, using it together with Nextcloud.

```
  onlyoffice:                                                                                                                                                                
    container_name: onlyoffice                                                                                                                                               
    image: onlyoffice/documentserver                                                                                                                                         
    expose:                                                                                                                                                                  
    - "80"                                                                                                                                                                   
    restart: always                                                                                                                                                          
```

If I manually restart nginx inside the container it works again for a day or so. (`service nginx start`)
