### ISSUE TITLE
Enviroment variables do not change port

### ISSUE THREAD

**Issue by casKd-dev** [ONLYOFFICE/Docker-DocumentServer#151]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
The document server tries to use the default port and localhost as connection even though `POSTGRESQL_SERVER_HOST` and `POSTGRESQL_SERVER_PORT` are defined.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. Use latest docker image
2. Define the two variables
3. Compose up

**What is the expected behavior?**

The document server would use the ports defined

**Did this work in previous versions of DocumentServer?**

Not tested

**DocumentServer Docker tag:**

onlyoffice/documentserver:5.2.8.24 (latest)

**Host Operating System:**

Ubuntu 16.04 xenial
x86_64 Linux 4.4.0-142-generic

**Comment by ShockwaveNN** [comment]
Seem trouble actual only for compose
Tred to use docker run env - and everything fine
```
docker run -it -p 80:80 -e POSTGRESQL_SERVER_HOST=192.168.1.1 -e POSTGRESQL_SERVER_PORT=1234 onlyoffice/documentserver:latest
Waiting for connection to the 192.168.1.1 host on port 1234
```

> Define the two variables

How did you define them? Do you edit docker-compose or somehow else?

**Comment by casKd-dev** [comment]
> Seem trouble actual only for compose
> Tred to use docker run env - and everything fine

I actually used also docker run with the variables too, same result. Here is what i've tried:

**docker-compose.yml**
```
version: '2'
services:
  documentserver:
    image: onlyoffice/documentserver:latest
    environment:
      - HTTP_CHECK=GET office.redxen.eu/healthcheck
      - EXTRA_SETTINGS=http-check expect string true
      #- POSTGRESQL_SERVER_HOST=HOST
      #- POSTGRESQL_SERVER_PORT=PORT
      #- POSTGRESQL_SERVER_DB_NAME=onlyoffice
      #- POSTGRESQL_SERVER_USER=onlyoffice
      #- POSTGRESQL_SERVER_PASS=PASSWORD
    stdin_open: true
    restart: always
    ports:
      - 3777:80
    volumes:
       - ./config/local.json:/etc/onlyoffice/documentserver/local.json
```

**docker run**
`docker run -e POSTGRESQL_SERVER_HOST=HOST -e POSTGRESQL_SERVER_PORT=PORT -e POSTGRESQL_SERVER_DB_NAME=onlyoffice -e POSTGRESQL_SERVER_USER=onlyoffice -e POSTGRESQL_SERVER_PASSWORD=PASSWORD -v /root/onlyoffice/config/local.json:/etc/onlyoffice/documentserver/local.json onlyoffice/documentserver:latest`

**Comment by ShockwaveNN** [comment]
@casKd-dev try to run your command without mounting `local.json`

**Comment by casKd-dev** [comment]
> @casKd-dev try to run your command without mounting `local.json`

Did that, no change. Forgot to add that the host is properly set.
So `POSTGRESQL_SERVER_HOST` is working but `POSTGRESQL_SERVER_PORT` is not. Maybe the variable has been changed?

**Comment by casKd-dev** [comment]
For some reason it now uses the correct port.

**Comment by casKd-dev** [comment]
Coming back up, it seems to have a extremly weird behaviour, it was not using the correct port indeed. Other than that it uses everything correctly. I get a connection refused as it still tries to use the default port.

Oddly enough, later connections work, they use the local.json which has identical entries for user and such.
This can be seen clearly as it attempts to query some stuff, but wrote nothing, not even a line.
The problem here is the initial connection.



![image](https://user-images.githubusercontent.com/30688640/54297537-65c12800-45b7-11e9-9326-6e6ca9775183.png)

**Comment by casKd-dev** [comment]
Okay, after a full re-install the port is still not defined. This needs some testing as i am not really sure where the problem really is.

docker-compose.yml related part:
```
documentserver:
    image: onlyoffice/documentserver
    environment:
      POSTGRESQL_SERVER_HOST: 'xxxxx'
      POSTGRESQL_SERVER_PORT: '31002'
      POSTGRESQL_SERVER_DB_NAME: 'onlyoffice'
      POSTGRESQL_SERVER_USER: 'onlyoffice'
      POSTGRESQL_SERVER_PASS: 'xxxxx'
      REDIS_SERVER_HOST: 'xxxxx'
      REDIS_SERVER_PORT: 'xxxxx'
      JWT_ENABLED: 'true'
      JWT_SECRET: 'xxxxxxxxxxxxx'
    ports:
    - target: 80
      published: xxxxx
      protocol: tcp
      mode: host
    stdin_open: true
```
The log output when starting the container:
```
Usage: grep [OPTION]... PATTERN [FILE]...
Try 'grep --help' for more information.
psql: could not connect to server: Connection timed out
 Is the server running on host "xxxxxxx" and accepting
 TCP/IP connections on port 5432?
```

**Comment by ShockwaveNN** [comment]
@casKd-dev Hi, I'm still was not able to reproduce your issue, could you provide minimal `docker-compose.yml` file in which your problem is reproduces?

**Comment by ShockwaveNN** [comment]
Oops, sorry didn't mean to close it

**Comment by casKd-dev** [comment]
```
version: '3.7'
documentserver:
    image: onlyoffice/documentserver:latest
    stdin_open: true
    environment:
      #POSTGRESQL_SERVER_HOST: 'localhost'
      #POSTGRESQL_SERVER_PORT: '5432'
      #POSTGRESQL_SERVER_DB_NAME: 'onlyoffice'
      #POSTGRESQL_SERVER_USER: 'onlyoffice'
      #POSTGRESQL_SERVER_PASS: 'password'
      REDIS_SERVER_HOST: 'localhost'
      REDIS_SERVER_PORT: '6377'
      JWT_ENABLED: 'true'
      JWT_SECRET: 'password111'
    ports:
    - '8080:80'
```
