### ISSUE TITLE
onlyoffice-documentserver_1 | Waiting for connection to the localhost host on port 5432

### ISSUE THREAD

**Issue by Gragoro** [ONLYOFFICE/Docker-DocumentServer#169]
**Hi**

Got a bug on two similar configurations with the new office deploying in the second case it happens. And at first everything works.

log docker

"onlyoffice-documentserver_1 | Waiting for connection to the localhost host on port 5432"

```
version: '2'
services:
  onlyoffice-documentserver-data:
    container_name: onlyoffice-documentserver-data
    image: onlyoffice/documentserver:latest
    environment:
      - ONLYOFFICE_DATA_CONTAINER=true
      - POSTGRESQL_SERVER_HOST=onlyoffice-postgresql
      - POSTGRESQL_SERVER_PORT=5432
      - POSTGRESQL_SERVER_DB_NAME=onlyoffice
      - POSTGRESQL_SERVER_USER=onlyoffice
      - POSTGRESQL_SERVER_PASSWORD=onlyoffice
      - RABBITMQ_SERVER_URL=amqp://guest:guest@onlyoffice-rabbitmq
      - REDIS_SERVER_HOST=onlyoffice-redis
      - REDIS_SERVER_PORT=6379
    stdin_open: true
    restart: always
    networks:
      - onlyoffice
    volumes:
      - /data/cloud/docker/onlyoffice/Data:/var/www/onlyoffice/Data
      - /data/cloud/docker/onlyoffice/log:/var/log/onlyoffice
      - /data/cloud/docker/onlyoffice/cache/files:/var/lib/onlyoffice/documentserver/App_Data/cache/files
      - /data/cloud/docker/onlyoffice/documentserver-example:/var/www/onlyoffice/documentserver-example/public/files
      - /data/cloud/docker/onlyoffice/fonts:/usr/share/fonts
      
  onlyoffice-documentserver:
    image: onlyoffice/documentserver:latest
    depends_on:
      - onlyoffice-documentserver-data
      - onlyoffice-postgresql
      - onlyoffice-redis
      - onlyoffice-rabbitmq
    environment:
      - ONLYOFFICE_DATA_CONTAINER_HOST=onlyoffice-documentserver-data
      - BALANCE=uri depth 3
      - EXCLUDE_PORTS=443
      - HTTP_CHECK=GET /healthcheck
      - EXTRA_SETTINGS=http-check expect string true
      - "VIRTUAL_HOST="all ok"
      - "LETSENCRYPT_HOST="all ok"
      - "LETSENCRYPT_EMAIL="all ok)"
    stdin_open: true
    restart: always   
    networks:
      - onlyoffice
    volumes_from:
      - onlyoffice-documentserver-data
     
  onlyoffice-redis:
    container_name: onlyoffice-redis
    image: redis
    restart: always
    networks:
      - onlyoffice
    expose:
      - '6379'

  onlyoffice-rabbitmq:
    container_name: onlyoffice-rabbitmq
    image: rabbitmq
    restart: always
    networks:
      - onlyoffice
    expose:
      - '5672'

  onlyoffice-postgresql:
    container_name: onlyoffice-postgresql
    image: postgres:9.5
    restart: always
    environment:
      - POSTGRES_DB=onlyoffice
      - POSTGRES_USER=onlyoffice
      - POSTGRES_PASSWORD=onlyoffice
    networks:
      - onlyoffice
    expose:
      - '5432'
    volumes:
      - postgresql_data:/var/lib/postgresql

networks:
  onlyoffice:
    driver: 'bridge'

volumes:
  postgresql_data:

```

**Comment by ShockwaveNN** [comment]
@Gragoro Hi, first thing - you got typo in your example on letsencryp line - extra `"`

Fixed variant will be 
```
version: '2'
services:
  onlyoffice-documentserver-data:
    container_name: onlyoffice-documentserver-data
    image: onlyoffice/documentserver:latest
    environment:
      - ONLYOFFICE_DATA_CONTAINER=true
      - POSTGRESQL_SERVER_HOST=onlyoffice-postgresql
      - POSTGRESQL_SERVER_PORT=5432
      - POSTGRESQL_SERVER_DB_NAME=onlyoffice
      - POSTGRESQL_SERVER_USER=onlyoffice
      - POSTGRESQL_SERVER_PASSWORD=onlyoffice
      - RABBITMQ_SERVER_URL=amqp://guest:guest@onlyoffice-rabbitmq
      - REDIS_SERVER_HOST=onlyoffice-redis
      - REDIS_SERVER_PORT=6379
    stdin_open: true
    restart: always
    networks:
      - onlyoffice
    volumes:
      - /data/cloud/docker/onlyoffice/Data:/var/www/onlyoffice/Data
      - /data/cloud/docker/onlyoffice/log:/var/log/onlyoffice
      - /data/cloud/docker/onlyoffice/cache/files:/var/lib/onlyoffice/documentserver/App_Data/cache/files
      - /data/cloud/docker/onlyoffice/documentserver-example:/var/www/onlyoffice/documentserver-example/public/files
      - /data/cloud/docker/onlyoffice/fonts:/usr/share/fonts
      
  onlyoffice-documentserver:
    image: onlyoffice/documentserver:latest
    depends_on:
      - onlyoffice-documentserver-data
      - onlyoffice-postgresql
      - onlyoffice-redis
      - onlyoffice-rabbitmq
    environment:
      - ONLYOFFICE_DATA_CONTAINER_HOST=onlyoffice-documentserver-data
      - BALANCE=uri depth 3
      - EXCLUDE_PORTS=443
      - HTTP_CHECK=GET /healthcheck
      - EXTRA_SETTINGS=http-check expect string true
      - VIRTUAL_HOST="all ok"
      - LETSENCRYPT_HOST="all ok"
      - LETSENCRYPT_EMAIL="all ok)"
    stdin_open: true
    restart: always   
    networks:
      - onlyoffice
    volumes_from:
      - onlyoffice-documentserver-data
     
  onlyoffice-redis:
    container_name: onlyoffice-redis
    image: redis
    restart: always
    networks:
      - onlyoffice
    expose:
      - '6379'

  onlyoffice-rabbitmq:
    container_name: onlyoffice-rabbitmq
    image: rabbitmq
    restart: always
    networks:
      - onlyoffice
    expose:
      - '5672'

  onlyoffice-postgresql:
    container_name: onlyoffice-postgresql
    image: postgres:9.5
    restart: always
    environment:
      - POSTGRES_DB=onlyoffice
      - POSTGRES_USER=onlyoffice
      - POSTGRES_PASSWORD=onlyoffice
    networks:
      - onlyoffice
    expose:
      - '5432'
    volumes:
      - postgresql_data:/var/lib/postgresql

networks:
  onlyoffice:
    driver: 'bridge'

volumes:
  postgresql_data:
```

And could you specify if I understand you right.
You got two servers. Both use same `docker-compose`
One server works, second server fails to run with `Waiting for connection to the localhost host on port 5432`?
If so you should compare content of mounting points
