### ISSUE TITLE
SSL Ports doesn't answer

### ISSUE THREAD

**Issue by blackerking** [ONLYOFFICE/Docker-DocumentServer#189]
I've copied valid crt, key and pem files like described into:
`/app/onlyoffice/DocumentServer/data/certs`
But the SSL ports doesn't respond - port 80 does.
Log files has no entrys.
Also tryied to changed permission for all files -> no solution.

I've checked some configuration of nginx but found nothing.
I can't access `/var/www/onlyoffice/Data/certs` inside the container. Is this normal?

My docker commands are:
`docker run -i -t -d -p 8280:443 -p 8180:80 onlyoffice/documentserver \ -v /app/onlyoffice/DocumentServer/data:/var/www/onlyoffice/Data`

changing ports doesn't change anything.

Ubuntu LTS 18.10
Nextcloud installed directly
ONLYOFFICE as Docker Image.

**Comment by ShockwaveNN** [comment]
Hi

> I can't access /var/www/onlyoffice/Data/certs inside the container. Is this normal?

Not, this is not normal, seems there is some permission problem with `/app/onlyoffice/DocumentServer/data` on host

**Comment by NorseGaud** [comment]
> Hi
> 
> > I can't access /var/www/onlyoffice/Data/certs inside the container. Is this normal?
> 
> Not, this is not normal, seems there is some permission problem with `/app/onlyoffice/DocumentServer/data` on host

What do they need to be?

**Comment by NorseGaud** [comment]
Same problem here.

**Comment by ShockwaveNN** [comment]
> I can't access /var/www/onlyoffice/Data/certs inside the container

You should be able to read from this dir in container by default container user at least

**Comment by blackerking** [comment]
I changed my configuration from docker cli to docker-compose.
-with success-
```
onlyoffice:
    image: onlyoffice/documentserver
    restart: always
    volumes:
      - /etc/apache2/ssl-oo:/var/www/onlyoffice/Data
    ports:
      - "8280:443"
      - "8180:80"
```
