### ISSUE TITLE
Restarting document server containers causes "An error has occurred while opening the file"

### ISSUE THREAD

**Issue by NorseGaud** [ONLYOFFICE/Docker-DocumentServer#225]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

1. Create a new docx and add "blah" as content
2. I stop the containers: `cd ~/x/onlyoffice-documentserver && docker-compose down `
3. I then start the container: `cd ~/x/onlyoffice-documentserver && docker-compose pull && docker-compose up -d`
3. I try to load the docx again and it shows:
<img width="412" alt="Screen Shot 2020-02-20 at 8 18 29 PM" src="https://user-images.githubusercontent.com/5896030/74995426-de16a700-541e-11ea-87c7-42d8fe28216a.png">

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

```
version: '3'
services:

  onlyoffice-documentserver:
    container_name: onlyoffice-documentserver
    image: onlyoffice/documentserver:latest
    depends_on:
      - onlyoffice-postgresql
      - onlyoffice-redis
      - onlyoffice-rabbitmq
    environment:
      - POSTGRESQL_SERVER_HOST=onlyoffice-postgresql
      - POSTGRESQL_SERVER_PORT=5432
      - POSTGRESQL_SERVER_DB_NAME=onlyoffice
      - POSTGRESQL_SERVER_USER=onlyoffice
      - POSTGRES_PASSWORD=onlyoffice
      - AMQP_SERVER_URL=amqp://guest:guest@onlyoffice-rabbitmq
      - REDIS_SERVER_HOST=onlyoffice-redis
      - REDIS_SERVER_PORT=6379
      - VIRTUAL_HOST=onlyoffice-ds.x.com
      - LETSENCRYPT_HOST=onlyoffice-ds.x.com
      - LETSENCRYPT_EMAIL=blah@blah.com
      # Uncomment the string below to redirect HTTP request to HTTPS request.
      #- FORCE_SSL=true
    stdin_open: true
    tty: true
    restart: always
    expose:
      - "80"
      - "443"
    networks:
      - default
      - onlyoffice
    volumes:
      - ./run-document-server.sh:/app/ds/run-document-server.sh
      - onlyoffice_etc:/etc/onlyoffice
      - onlyoffice_data:/var/www/onlyoffice/Data
      - onlyoffice_logs:/var/log/onlyoffice
      - /var/lib/onlyoffice/documentserver/App_Data/cache/files
      - /var/www/onlyoffice/documentserver-example/public/files
      - /usr/share/fonts
      # - ./ds.conf.tmpl:/etc/onlyoffice/documentserver/nginx/ds.conf.tmpl
      - webproxy_certs:/var/www/onlyoffice/Data/certs

  onlyoffice-redis:
    container_name: onlyoffice-redis
    image: redis
    restart: always
    networks:
     - onlyoffice
    expose:
      - '6379'

  onlyoffice-rabbitmq:
    container_name: onlyoffice-rabbitmq
    image: rabbitmq
    restart: always
    networks:
     - onlyoffice
    expose:
      - '5672'

  onlyoffice-postgresql:
    container_name: onlyoffice-postgresql
    image: postgres:9.5
    environment:
      - POSTGRES_DB=onlyoffice
      - POSTGRES_USER=onlyoffice
      - POSTGRES_PASSWORD=1234567
    networks:
      - onlyoffice
    restart: always
    expose:
      - '5432'
    volumes:
      - /root/onlyoffice_postgresql_data:/var/lib/postgresql/data

volumes:
  onlyoffice_data:
  onlyoffice_logs:
  onlyoffice_etc:
  mysql_data:
  webproxy_certs:
    external: true

networks:
  default:
    external:
      name: webproxy
  onlyoffice:
    driver: 'bridge'
```

**What is the expected behavior?**
Documents load properly

**Did this work in previous versions of DocumentServer?**
Not sure

**DocumentServer Docker tag:**
onlyoffice/documentserver:latest

**Host Operating System:**
Linux 4.15.0-74-generic #84-Ubuntu

**Comment by ShockwaveNN** [comment]
Could you look out for any errors in `/var/log/onlyoffice`

**Comment by NorseGaud** [comment]
Here is one thing I found:
`tail -100 /var/log/onlyoffice/documentserver/converter/out.log`
```
[2020-02-21T10:11:06.825] [ERROR] nodeJS - stdout (id=3877597986_4630):
[2020-02-21T10:11:06.825] [ERROR] nodeJS - stderr (id=3877597986_4630):Couldn't automatically recognize conversion direction from extensions

[2020-02-21T10:11:06.825] [ERROR] nodeJS - ExitCode (code=88;signal=null;error:-80;id=3877597986_4630)
```

`tail -f /var/log/onlyoffice/documentserver/docservice/out.log`
```
[2020-02-21T10:13:35.988] [ERROR] nodeJS - sendServerRequest error: docId = 3877597986;url = https://nextcloud.xkr.email/apps/onlyoffice/track?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiJuYXRoYW4ucGllcmNlIiwiZmlsZUlkIjoyMDIyLCJmaWxlUGF0aCI6IlwvdGVzdGluZy5kb2N4Iiwic2hhcmVUb2tlbiI6bnVsbCwiYWN0aW9uIjoidHJhY2sifQ.qksqyLUvxVxD1eUQutKSxba4t-iOsznG_Js19IPzVLo;data = {"key":"3877597986","status":3,"users":["ochmr3mbs1sy_nathan.pierce"],"actions":[{"type":0,"userid":"ochmr3mbs1sy_nathan.pierce"}],"lastsave":"2020-02-21T10:13:35.741Z","notmodified":false}
Error: Error response: statusCode:400 ;body:
{"message":"Url not found"}
    at Request._callback (/var/www/onlyoffice/documentserver/server/Common/sources/utils.js:301:23)
    at Request.self.callback (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
```

**Comment by NorseGaud** [comment]
Here is one thing I found:
`tail -100 /var/log/onlyoffice/documentserver/converter/out.log`
```
[2020-02-21T10:11:06.825] [ERROR] nodeJS - stdout (id=3877597986_4630):
[2020-02-21T10:11:06.825] [ERROR] nodeJS - stderr (id=3877597986_4630):Couldn't automatically recognize conversion direction from extensions

[2020-02-21T10:11:06.825] [ERROR] nodeJS - ExitCode (code=88;signal=null;error:-80;id=3877597986_4630)
```

`tail -f /var/log/onlyoffice/documentserver/docservice/out.log`
```
[2020-02-21T10:13:35.988] [ERROR] nodeJS - sendServerRequest error: docId = 3877597986;url = https://nextcloud.x.com/apps/onlyoffice/track?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiJuYXRoYW4ucGllcmNlIiwiZmlsZUlkIjoyMDIyLCJmaWxlUGF0aCI6IlwvdGVzdGluZy5kb2N4Iiwic2hhcmVUb2tlbiI6bnVsbCwiYWN0aW9uIjoidHJhY2sifQ.qksqyLUvxVxD1eUQutKSxba4t-iOsznG_Js19IPzVLo;data = {"key":"3877597986","status":3,"users":["ochmr3mbs1sy_nathan.pierce"],"actions":[{"type":0,"userid":"ochmr3mbs1sy_nathan.pierce"}],"lastsave":"2020-02-21T10:13:35.741Z","notmodified":false}
Error: Error response: statusCode:400 ;body:
{"message":"Url not found"}
    at Request._callback (/var/www/onlyoffice/documentserver/server/Common/sources/utils.js:301:23)
    at Request.self.callback (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
```

**Comment by ShockwaveNN** [comment]
Seems this is a reason
```
[2020-02-21T10:13:35.988] [ERROR] nodeJS - sendServerRequest error: docId = 3877597986;url = https://nextcloud.x.com/apps/onlyoffice/track?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiJuYXRoYW4ucGllcmNlIiwiZmlsZUlkIjoyMDIyLCJmaWxlUGF0aCI6IlwvdGVzdGluZy5kb2N4Iiwic2hhcmVUb2tlbiI6bnVsbCwiYWN0aW9uIjoidHJhY2sifQ.qksqyLUvxVxD1eUQutKSxba4t-iOsznG_Js19IPzVLo;data = {"key":"3877597986","status":3,"users":["ochmr3mbs1sy_nathan.pierce"],"actions":[{"type":0,"userid":"ochmr3mbs1sy_nathan.pierce"}],"lastsave":"2020-02-21T10:13:35.741Z","notmodified":false}
Error: Error response: statusCode:400 ;body:
```
DocumentServer couldn't connect to nextcloud
Could you check that DocumentServer can open files from integrated test example (but for test purposes you should replace `onlyoffice-documentserver` container to `onlyoffice-documentserver-de`

**Comment by NorseGaud** [comment]
Thanks for the help!
Sorry, what do you mean by an integrated test example? Where/what is that?
Also, what is the reason for the container name change?

Here is my nextcloud docker file if it helps:
```
version: '3'
services:

  nextcloud-app:
    image: nextcloud:latest
    container_name: nextcloud-app
    environment:
      - VIRTUAL_HOST=nextcloud.x.com
      - VIRTUAL_NETWORK=nextcloud-nginx-proxy
      - LETSENCRYPT_HOST=nextcloud.x.com
      - LETSENCRYPT_EMAIL=blah@blah.com
      - MYSQL_HOST=nextcloud-db
    volumes:
      - /root/nextcloud_apps:/var/www/html/apps
      - /root/nextcloud_custom_apps:/var/www/html/custom_apps
      - /root/nextcloud_config:/var/www/html/config
      - /root/nextcloud_data:/var/www/html/data
    expose:
      - "80"
      - "443"
    stdin_open: true
    tty: true
    networks:
      - default
      - nextcloud
    restart: always
    env_file:
      - db.env
    depends_on:
      - nextcloud-db

  nextcloud-db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    container_name: nextcloud-db
    volumes:
      - /root/nextcloud_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=XXXXXXXXXXXXXXXXXXX
    networks:
      - nextcloud
    restart: always
    env_file:
      - db.env

networks:
  default:
    external:
      name: webproxy
  nextcloud:
    driver: 'bridge'


```

**Comment by NorseGaud** [comment]
I wanted to also mention that I'm doing the `docker exec <CONTAINER> documentserver-prepare4shutdown.sh` before shutting it down.

**Comment by ShockwaveNN** [comment]
> an integrated test example? Where/what is that?

This one:
![image](https://user-images.githubusercontent.com/668524/75035665-1078e080-54c1-11ea-966d-2a463e1b57ae.png)

Opening files in this example can detect if something wrong with DocumentServer itself if test example cause same error
It available via running instruction on `https://documentserver/welcome/`

> Also, what is the reason for the container name change?

Because test example is not available by default with `onlyoffice-documentserver` image, only with `onlyoffice-documentserver-ie` or `onlyoffice-documentserver-de`

**Comment by NorseGaud** [comment]
Odd, I'm using `image: onlyoffice/documentserver-de:latest` and also -ie and the welcome page doesn't show anything about a test. :(
All I see is 
<img width="649" alt="Screen Shot 2020-02-21 at 8 11 21 AM" src="https://user-images.githubusercontent.com/5896030/75037284-cd4b4d00-5481-11ea-8021-0a5221486ec4.png">

**Comment by NorseGaud** [comment]
Does the actual container name need to change too? Or just the image being used?

**Comment by ShockwaveNN** [comment]
> Odd, I'm using image: onlyoffice/documentserver-de:latest and also -ie and the welcome page doesn't show anything about a test. :(

Try to clear browser cache, this is not right

> Does the actual container name need to change too? Or just the image being used?

No, only image name

**Comment by NorseGaud** [comment]
Hmm... No difference. Is there documentation on these tags/images somewhere? Maybe I'm missing an ENV

**Comment by ShockwaveNN** [comment]
> Hmm... No difference.

To be sure - are you geting same "An error has occured" while using integrated test example?

**Comment by NorseGaud** [comment]
I meant that clearing the cache doesn't show the page that will allow me to do the integrated test.

**Comment by ShockwaveNN** [comment]
Ok, try to drop `docker-compose` and only use clear `onlyoffice/documentserver` container and connect it to your nextcloud and see if it works
If will not work at least reason not in compose part

**Comment by NorseGaud** [comment]
Playing a little more with my docker-compose setup, I see a new error now:

```
==> /var/log/onlyoffice/documentserver/docservice/out.log <==
==> /var/log/onlyoffice/documentserver/docservice/out.log <==
[2020-02-23T01:32:58.183] [ERROR] nodeJS - sendServerRequest error: docId = 2091389658;url = https://nextcloud.x.com/apps/onlyoffice/track?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiJuYXRoYW4ucGllcmNlIiwiZmlsZUlkIjoyMDQ4LCJmaWxlUGF0aCI6IlwvMTIzLmRvY3giLCJzaGFyZVRva2VuIjpudWxsLCJhY3Rpb24iOiJ0cmFjayJ9.qjw-Opr47l6CAhsJMPIgC6hWKF9QAgLjeySg4HyVVOo;data = {"key":"2091389658","status":2,"url":"https://onlyoffice-ds.x.com/cache/files/2091389658_7103/output.docx/output.docx?md5=ITa1oNBMBUUIYedajB0agg&expires=1582422479&disposition=attachment&ooname=output.docx","changesurl":"https://onlyoffice-ds.x.com/cache/files/2091389658_7103/changes.zip/changes.zip?md5=91Hq0pftW8G4QDijCVOI7g&expires=1582422479&disposition=attachment&ooname=output.zip","history":{"serverVersion":"5.4.2","changes":[{"created":"2020-02-23 00:37:49","user":{"id":"ochmr3mbs1sy_nathan.pierce","name":"Nathan Pierce"}}]},"users":["ochmr3mbs1sy_nathan.pierce"],"actions":[{"type":0,"userid":"ochmr3mbs1sy_nathan.pierce"}],"lastsave":"2020-02-23T00:37:49.649Z","notmodified":false}
Error: socket hang up
    at createHangUpError (_http_client.js:342:15)
    at TLSSocket.socketOnEnd (_http_client.js:437:23)
    at emitNone (events.js:111:20)
    at TLSSocket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
```

**Comment by NorseGaud** [comment]
Thanks @ShockwaveNN 
There are a lot of options I have to pass in to get it running with `docker run`. I'll try it out, but I'm sort of out of steam right now so I'm going to take a break.

**Comment by ShockwaveNN** [comment]
@NorseGaud
> Error: socket hang up

I think this is some kind of network problem, maybe some firewall block, I'm not sure

**Comment by NorseGaud** [comment]
@ShockwaveNN do you have any other ideas around why the -de and -ie don't work?

**Comment by ShockwaveNN** [comment]
@NorseGaud No, no idea, I could take a look into your setup if you provide VM image or step-by-step instruction how did you setup all the services (DocumentServer and Nextcloud)

**Comment by NorseGaud** [comment]
Sure, so both docker-compose files are provided above. I just `docker-compose up -d` them.

**Comment by NorseGaud** [comment]
You'll need the webproxy too:

```
version: '3'
services:

  webproxy-nginx:
    container_name: webproxy-nginx
    image: nginx
    labels:
        com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf.d:/etc/nginx/conf.d
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /root/webproxy_certs:/etc/nginx/certs:ro
      - htpasswd:/etc/nginx/htpasswd:ro
    logging:
      options:
        max-size: "4m"
        max-file: "10"

  webproxy-nginx-gen:
    image: jwilder/docker-gen
    command: -notify-sighup webproxy-nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: webproxy-nginx-gen
    restart: always
    volumes:
      - conf.d:/etc/nginx/conf.d
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /root/webproxy_certs:/etc/nginx/certs:ro
      - htpasswd:/etc/nginx/htpasswd:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
    logging:
      options:
        max-size: "2m"
        max-file: "10"

  webproxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: webproxy-letsencrypt
    restart: always
    volumes:
      - conf.d:/etc/nginx/conf.d
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /root/webproxy_certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_DOCKER_GEN_CONTAINER: webproxy-nginx-gen
      NGINX_PROXY_CONTAINER: webproxy-nginx
    logging:
      options:
        max-size: "2m"
        max-file: "10"

volumes:
  vhost.d:
  conf.d:
  html:
  htpasswd:

networks:
  default:
    external:
      name: webproxy
```
