### ISSUE TITLE
document-server behind jwilder/nginx-proxy

### ISSUE THREAD

**Issue by webparadoxer** [ONLYOFFICE/Docker-DocumentServer#262]
I have some trouble. This is my docker-compose.
All worked on http://ip:84/ - redirect, connection with owncloud, but https://doc.me.dev - give 502 error
How can i fix this?

```
version: '3.1'

networks:
    proxy:
        external:
            name: proxy

services:
  onlyoffice-document-server:
    container_name: onlyoffice-document-server
    image: onlyoffice/documentserver:latest
    restart: always
    stdin_open: true
    ports:
      - 84:80
    environment:
      - VIRTUAL_HOST=doc.me.dev
      - VIRTUAL_PORT=84
      - LETSENCRYPT_HOST=doc.me.dev
      - LETSENCRYPT_EMAIL=me@doc.dev
    networks:
      - proxy

```
