### ISSUE TITLE
Docker Networking Issue

### ISSUE THREAD

**Issue by typkrft** [ONLYOFFICE/Docker-DocumentServer#308]
I am able to reach nextcloud at nextcloud.mySecret.url and it appears to function normally. I am able to reach onlyoffice at office.mySecret.url and I see the green check mark. I see `true` for healthstatus. If someone could point me in the right direction it would be greatly appreciated. 

** I am not able to curl from one docker container to the other. I think this might be the issue but am un sure of how to fix it. **

ERROR MSG
```
Error when trying to connect (Error occurred in the document service: Error while downloading the document file to be converted.) (version [6.0.1.32](https://6.0.1.32))✖
```
traefik.yml
```
version: "3.7"

########################### NETWORKS
networks:
  t2_proxy:
    external:
      name: t2_proxy
  default:
    driver: bridge

########################### SERVICES
services:
# All services / apps go below this line

# Traefik 2 - Reverse Proxy
  traefik:
    container_name: traefik
    image: traefik:2.2.1 # the chevrotin tag refers to v2.2.x but introduced a breaking change in 2.2.2
    restart: unless-stopped

    command: # CLI arguments
      - --global.checkNewVersion=true
      - --global.sendAnonymousUsage=true
      - --entryPoints.http.address=:80
      - --entryPoints.https.address=:443
        # Allow these IPs to set the X-Forwarded-* headers - Cloudflare IPs: https://www.cloudflare.com/ips/
      - --entrypoints.https.forwardedHeaders.trustedIPs=173.245.48.0/20,103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,141.101.64.0/18,108.162.192.0/18,190.93.240.0/20,188.114.96.0/20,197.234.240.0/22,198.41.128.0/17,162.158.0.0/15,104.16.0.0/12,172.64.0.0/13,131.0.72.0/22
      - --entryPoints.traefik.address=:8080
      - --api=true
#      - --api.insecure=true
#      - --serversTransport.insecureSkipVerify=true
      - --log=true
      - --log.level=DEBUG # (Default: error) DEBUG, INFO, WARN, ERROR, FATAL, PANIC
      - --accessLog=true
      - --accessLog.filePath=/traefik.log
      - --accessLog.bufferingSize=100 # Configuring a buffer of 100 lines
      - --accessLog.filters.statusCodes=400-499
      - --providers.docker=true
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --providers.docker.defaultrule=Host(`{{ index .Labels "com.docker.compose.service" }}.$DOMAINNAME`)
      - --providers.docker.exposedByDefault=false
      - --providers.docker.network=t2_proxy
      - --providers.docker.swarmMode=false
      - --providers.file.directory=/rules # Load dynamic configuration from one or more .toml or .yml files in a directory.
#      - --providers.file.filename=/path/to/file # Load dynamic configuration from a file.
      - --providers.file.watch=true # Only works on top level files in the rules folder
#      - --certificatesResolvers.dns-cloudflare.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory # LetsEncrypt Staging Server - uncomment when testing
      - --certificatesResolvers.dns-cloudflare.acme.email=$CLOUDFLARE_EMAIL
      - --certificatesResolvers.dns-cloudflare.acme.storage=/acme.json
      - --certificatesResolvers.dns-cloudflare.acme.dnsChallenge.provider=cloudflare

    networks:
      t2_proxy:
        ipv4_address: 192.168.90.254 # You can specify a static IP
#    networks:
#      - t2_proxy

    security_opt:
      - no-new-privileges:true

    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host

    volumes:
      - $DOCKERDIR/traefik2/rules:/rules 
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $DOCKERDIR/traefik2/acme/acme.json:/acme.json 
      - $DOCKERDIR/traefik2/traefik.log:/traefik.log 
      - $DOCKERDIR/shared:/shared
    
    environment:
      - CF_API_EMAIL=$CLOUDFLARE_EMAIL
      - CF_API_KEY=$CLOUDFLARE_API_KEY

    labels:
      - "traefik.enable=true"

      # HTTP-to-HTTPS Redirect
      - "traefik.http.routers.http-catchall.entrypoints=http"
      - "traefik.http.routers.http-catchall.rule=HostRegexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

      # HTTP Routers
      - "traefik.http.routers.traefik-rtr.entrypoints=https"
      - "traefik.http.routers.traefik-rtr.rule=Host(`traefik.$DOMAINNAME`)"
      - "traefik.http.routers.traefik-rtr.tls=true"
#      - "traefik.http.routers.traefik-rtr.tls.certresolver=dns-cloudflare" # Comment out this line after first run of traefik to force the use of wildcard certs
      - "traefik.http.routers.traefik-rtr.tls.domains[0].main=$DOMAINNAME"
      - "traefik.http.routers.traefik-rtr.tls.domains[0].sans=*.$DOMAINNAME"
#      - "traefik.http.routers.traefik-rtr.tls.domains[1].main=$SECONDDOMAINNAME" # Pulls main cert for second domain
#      - "traefik.http.routers.traefik-rtr.tls.domains[1].sans=*.$SECONDDOMAINNAME" # Pulls wildcard cert for second domain

      ## Services - API **NOTE: MAYBE UNNEEDED**
      - "traefik.http.routers.traefik-rtr.service=api@internal"
      
      ## Middlewares
      - "traefik.http.routers.traefik-rtr.middlewares=chain-basic-auth@file" 
      
```

onlyoffice.yml
```
version: "3.7"

########################### NETWORKS
networks:
  t2_proxy:
    external:
      name: t2_proxy
  default:
    driver: bridge
services:

services:
  onlyoffice:
    image: onlyoffice/documentserver:latest
    container_name: onlyoffice
    networks:
      - t2_proxy
    ports:
      - 1080:80
      - 10443:443
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"    
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.office-rtr.entrypoints=https"
      - "traefik.http.routers.office-rtr.rule=Host(`office.$DOMAINNAME`)"
      - "traefik.http.routers.office-rtr.tls=true"
      ## Middlewares
#      - "traefik.http.routers.office-rtr.middlewares=chain-oauth@file"
      - "traefik.http.routers.office-rtr.middlewares=chain-no-auth@file" # Basic Authentication
      ## HTTP Services
      - "traefik.http.routers.office-rtr.service=office-svc"
      - "traefik.http.services.office-svc.loadbalancer.server.port=80"
```

nextcloud.yml
```
version: "3.7"
services:

  nextcloud:
    container_name: nextcloud
    image: nextcloud:latest
    restart: always
    networks:
      - t2_proxy
    ports:
      - "9020:80"
    security_opt:
      - no-new-privileges:true
    volumes:
      - $DOCKERDIR/nextcloud/var:/var/www/html
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - MSQL_USER=$NEXTCLOUD_DB_USER
      - MYSQL_PASSWORD=$NEXTCLOUD_DB_PASSWORD
      - MYSQL_HOST=nextCloudDB
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.nextcloud-rtr.entrypoints=https"
      - "traefik.http.routers.nextcloud-rtr.rule=Host(`nextcloud.$DOMAINNAME`)"
      - "traefik.http.routers.nextcloud-rtr.tls=true"
      ## Middlewares
#      - "traefik.http.routers.nextcloud-rtr.middlewares=chain-oauth@file"
      - "traefik.http.routers.nextcloud-rtr.middlewares=chain-no-auth@file" # Basic Authentication
      ## HTTP Services
      - "traefik.http.routers.nextcloud-rtr.service=nextcloud-svc"
      - "traefik.http.services.nextcloud-svc.loadbalancer.server.port=80"
      
  nextCloudDB:
    container_name: nextCloudDB
    image: linuxserver/mariadb:latest
    restart: always
    networks:
      t2_proxy:
        ipv4_address: 192.168.90.249
    security_opt:
      - no-new-privileges:true
    ports:
      - "7306:3306"
    volumes:
      - $DOCKERDIR/nextCloudDB:/config
#      - /etc/timezone:/etc/timezone:ro
#      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=$TZ
      - PUID=$PUID
      - PGID=$PGID
      - MYSQL_ROOT_PASSWORD=$NEXTCLOUD_DB_ROOT_PASSWORD
      - MYSQL_USER=$NEXTCLOUD_DB_USER
      - MYSQL_DATABASE=nextCloudDB
      - MYSQL_PASSWORD=$NEXTCLOUD_DB_PASSWORD

networks:
  t2_proxy:
    external: true
```

config.php
```
<?php
$CONFIG = array (
  'htaccess.RewriteBase' => '/',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'apps_paths' =>
  array (
    0 =>
    array (
      'path' => '/var/www/html/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 =>
    array (
      'path' => '/var/www/html/custom_apps',
      'url' => '/custom_apps',
      'writable' => true,
    ),
  ),
  'instanceid' => 'ocjzpn5tfd1y',
  'passwordsalt' => 'SECRET',
  'secret' => 'SECRET',
  'trusted_domains' =>
  array (
    0 => 'nextcloud.mySecret.url',
    1 => 'office.mySecret.pw',
  ),
  'onlyoffice' =>
  array (
    'verify_peer_off' => TRUE,
  ),
  'datadirectory' => '/var/www/html/data',
  'dbtype' => 'mysql',
  'version' => '20.0.1.1',
  'overwrite.cli.url' => 'http://nextcloud.mySecret.url',
  'dbname' => 'nextCloudDB',
  'dbhost' => 'nextCloudDB',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'SECRET',
  'dbpassword' => 'SECRET',
  'installed' => true,
);
```
