### ISSUE TITLE
Runs without mySQL container!

### ISSUE THREAD

**Issue by zilexa** [ONLYOFFICE/Docker-DocumentServer#338]
I noticed DocumentServer runs fine without a mysql server. 
This is not mentioned in the documentation. Now I am wondering what the minimum set of arguments and variables is to have DocumentServer running?

This is my Docker Compose for OnlyOffice +rabbitmq, I left out my Caddy labels for https/reverse proxy (they work, but still haven an issue to open documents from FileRun (nextcloud alternative, also runs via Compose in the same network): 

```
  onlyoffice:
    image: onlyoffice/documentserver
    container_name: onlyoffice
    depends_on:
      #- onlyoffice-postgresql
      - onlyoffice-rabbitmq
    stdin_open: true
    restart: always
    networks: 
      - caddy
    tty: true
    ports:
      - "8889:80"
    volumes:
      - $USERDIR/docker/onlyoffice/data:/var/www/onlyoffice/Data
      - $USERDIR/docker/onlyoffice/log:/var/log/onlyoffice
      - $USERDIR/docker/onlyoffice/cache:/var/lib/onlyoffice/documentserver/App_Data/cache/files
      - $USERDIR/docker/onlyoffice/example:/var/www/onlyoffice/documentserver-example/public/files
      - $USERDIR/docker/onlyoffice/fonts:/usr/share/fonts
    dns: 1.1.1.1
    environment:
      - JWT_ENABLED="true"
      - JWT_SECRET=$ONLYOFFICEJWT
      #- DB_TYPE=postgres
      #- DB_HOST=onlyoffice-postgresql
      #- DB_PORT=5432
      #- DB_NAME=onlyoffice
      #- DB_USER=onlyoffice
      - AMQP_URI=amqp://guest:guest@onlyoffice-rabbitmq
  onlyoffice-rabbitmq:
    container_name: onlyoffice-rabbitmq
    image: rabbitmq
    restart: always
    networks: 
      - caddy
    expose:
      - '5672'
```
