### ISSUE TITLE
Nginx high memory consumption

### ISSUE THREAD

**Issue by witchent** [ONLYOFFICE/Docker-DocumentServer#367]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
The started Nginx instance of the DocumentServer is using a lot of memory (12% from my 4gb system).

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Just start the docker image.

**What is the expected behavior?**
I don't know why OnlyOffice has to start nginx at all (I am running another instance in front of it all, which is using less then 1% of memory), but at least it should not use that much memory.

**Did this work in previous versions of DocumentServer?**
No idea, just started using it

**DocumentServer Docker tag:**
6.3

**Host Operating System:**
Arch linux x64

**Comment by ShockwaveNN** [comment]
Are you sure it's nginx memory? We generate font data on container start and this is rather CPU and memory intensive operation

**Comment by witchent** [comment]
Well the process is called nginx and it's not going away even after 8 hours idling

**Comment by ShockwaveNN** [comment]
This is that I get on one of my servers, which no one used now

![image](https://user-images.githubusercontent.com/668524/124714564-9789f580-df0a-11eb-95d0-24ee92808f0b.png)

So look like your non-zero CPU somehow related to custom configs maybe? Which command you used to run docker image?

**Comment by witchent** [comment]
Well no I am talking about the memory consumption, not the CPU usage. CPU was fine for me as well.
I am using docker-compose, I can paste my config here later this afternoon when I am back at my server.

**Comment by ShockwaveNN** [comment]
Oh, sorry, confused CPU and memory, but on my screen there is 106M memory - I think it's good value too

Waiting for you config also please take a look at log files at `/var/log/onlyoffice`- maybe it's spamming errors and that cause higher than usual load

**Comment by witchent** [comment]
```
onlyoffice:
    container_name: onlyoffice
    image: onlyoffice/documentserver
    restart: on-failure
    depends_on:
      onlyoffice-postgres:
        condition: service_healthy
      onlyoffice-rabbitmq:
        condition: service_healthy
    environment:
      DB_TYPE: postgres
      DB_HOST: onlyoffice-postgres
      DB_PORT: 5432
      DB_NAME: onlyoffice
      DB_USER: postgres
      DB_PWD: gXQqyG7elFVP02Uvhz9A
      AMQP_URI: amqp://guest:guest@onlyoffice-rabbitmq
    ports:
      - '8523:80'
```

With this the nginx process is using 12% of my 4GB memory.
Adding 
```
      NGINX_WORKER_PROCESSES: 1
      NGINX_WORKER_CONNECTIONS: 512
```
to the environment variables actually fixes it without any noticeable differences. Do I have to expect a downside from this or should this be fine?
