### ISSUE TITLE
Server not working correctly when exposed on custom port

### ISSUE THREAD

**Issue by dawidgarus** [ONLYOFFICE/Docker-DocumentServer#432]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

OnlyOffice failes to open document in Nextcloud when it runs on port different than default.
In my case it's port 5XXXX. You can see that call for Editor.bin fails because it tries to connect on default port (443):
![Screenshot from 2022-04-28 00-00-17](https://user-images.githubusercontent.com/6207659/165639158-044298d4-4c94-48f5-8cf2-7d1003cc3da5.png)

I've noticed that the server struggles when you try to use it with different than default port.
For example, I've encountered the same issue as here: https://github.com/ONLYOFFICE/Docker-DocumentServer/issues/15 and it was supposed to be closed. Fortunately I've found a workaround to rewrite redirects in nginx (`proxy_redirect http://onlyoffice.DOMAIN.TLD/ https://onlyoffice.DOMAIN.TLD:5XXXX/;`)

And for anyone asking why I'm not running my server on port 443 - I can't. Port 5XXXX was assigned to me and it's the only way I can expose my server to the world (EDIT: fix typo)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Docker configuration:
```yaml
version: '3'
services:
  redis:
    image: redis:latest
    container_name: nextcloud-redis
    restart: unless-stopped
  db:
    image: postgres:latest
    container_name: nextcloud-postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=SECRET
      - POSTGRES_DB=nextcloud
    restart: unless-stopped
  app:
    image: nextcloud:latest
    container_name: nextcloud-app
    ports:
      - 8080:80
    depends_on:
      - db
      - redis
      - onlyoffice
    volumes:
      - ./nextcloud:/var/www/html
      - /etc/localtime:/etc/localtime:ro
    environment:
      - REDIS_HOST=redis
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=SECRET
      - POSTGRES_DB=nextcloud
      - POSTGRES_HOST=db
    restart: unless-stopped
  onlyoffice:
    image: onlyoffice/documentserver:latest
    container_name: nextcloud-onlyoffice
    ports:
      - 8081:80
    restart: unless-stopped
```

Nginx configuration:
```
upstream nextcloud {
    server host.docker.internal:8080;
}

server {
    listen       5XXXX ssl;
    server_name  nextcloud.DOMAIN.TLD;

    #access_log  /var/log/nginx/host.access.log  main;

    include /etc/nginx/ssl.conf;

    location / {
        proxy_pass http://nextcloud;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $remote_addr;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}

upstream onlyoffice {
    server host.docker.internal:8081;
}

server {
    listen       5XXXX ssl;
    server_name  onlyoffice.DOMAIN.TLD;

    #access_log  /var/log/nginx/host.access.log  main;

    include /etc/nginx/ssl.conf;

    location / {
        proxy_pass http://onlyoffice;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_redirect http://onlyoffice.DOMAIN.TLD/ https://onlyoffice.DOMAIN.TLD:5XXXX/;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}

```
Nextcloud onlyoffice plugin configuration:
![Screenshot from 2022-04-27 23-55-06](https://user-images.githubusercontent.com/6207659/165637732-643198cd-7b3e-4282-aaf5-9ef01125f490.png)

**What is the expected behavior?**

It should display document

**Did this work in previous versions of DocumentServer?**

I don't know

**DocumentServer Docker tag:**

latest

**Host Operating System:**

Open Media Vault 5.6.13
