### ISSUE TITLE
Error while downloading the document file to be converted.) (версия 7.1.0.215) - docker docker-compose

### ISSUE THREAD

**Issue by webagroprom** [ONLYOFFICE/Docker-DocumentServer#441]
Nextcloud Hub II 23.0.5 + Onlyoffice 

1. Open Nexcloud's config.php (by defauld /var/www/nextcloud/config/config.php)
Add this to the 2nd last line (before the line with );) and paste in your secret (3rd last line)

 ```
 'onlyoffice' =>
    array (
      "jwt_secret" => "123123123",
      "jwt_header" => "AuthorizationJwt"
  )
```
2. **create openssl self-signed certificate**
mkdir /app/onlyoffice/DocumentServer/data/certs
cp  /app/onlyoffice/DocumentServer/data/certs/onlyoffice.crt
cp  /app/onlyoffice/DocumentServer/data/certs/onlyoffice.key

4. **Edit file docker-compose.yml**4. 

```
      - JWT_ENABLED=true
      - JWT_SECRET=123123123
      - JWT_HEADER=AuthorizationJwt
      - JWT_IN_BODY=true
```

**full file docker-compose.yml**

```
version: '2'
services:
  onlyoffice-documentserver:
    image: jiriks74/onlyoffice-documentserver:latest
    container_name: onlyoffice-documentserver
    depends_on:
      - onlyoffice-postgresql
      - onlyoffice-rabbitmq
    environment:
      - DB_TYPE=postgres
      - DB_HOST=onlyoffice-postgresql
      - DB_PORT=5432
      - DB_NAME=onlyoffice
      - DB_USER=onlyoffice
      - AMQP_URI=amqp://guest:guest@onlyoffice-rabbitmq
      # Uncomment strings below to enable the JSON Web Token validation.
      - JWT_ENABLED=true
      - JWT_SECRET=123123123
      - JWT_HEADER=AuthorizationJwt
      - JWT_IN_BODY=true
      # Uncomment the line below to set larger file limits (about 1GB)
      #- LARGER_FILE_LIMITS=true
    ports:
      - '9050:80'
      - '9000:443'
    stdin_open: true
    restart: always
    stop_grace_period: 120s
    volumes:
       # Uncomment the line below to get access to the slide themes directory.
       # To use the themes, copy them to the slideThemes directory and run `docker exec -it <container-name> /usr/bin/documentserver-generate-allfonts.sh`
       #- ./slideThemes:/var/www/onlyoffice/documentserver/sdkjs/slide/themes/src
       #- /var/www/onlyoffice/Data
       #- /var/log/onlyoffice
       #- /var/lib/onlyoffice/documentserver/App_Data/cache/files
       #- /var/www/onlyoffice/documentserver-example/public/files
       #- /usr/share/fonts
        - /app/onlyoffice/DocumentServer/logs:/var/log/onlyoffice
        - /app/onlyoffice/DocumentServer/data:/var/www/onlyoffice/Data
        - /app/onlyoffice/DocumentServer/lib:/var/lib/onlyoffice
        - /app/onlyoffice/DocumentServer/db:/var/lib/postgresql

  onlyoffice-rabbitmq:
    container_name: onlyoffice-rabbitmq
    image: rabbitmq
    restart: always
    expose:
      - '5672'

  onlyoffice-postgresql:
    container_name: onlyoffice-postgresql
    image: postgres:9.5
    environment:
      - POSTGRES_DB=onlyoffice
      - POSTGRES_USER=onlyoffice
      - POSTGRES_HOST_AUTH_METHOD=trust
    restart: always
    expose:
      - '5432'
    volumes:
      - postgresql_data:/var/lib/postgresql

volumes:
  postgresql_data:
```

5. run docker-compose onlyoffice -
 **docker-compose up -d**

6. I go to the browser: https://localhost:9000
open: ONLYOFFICE Docs Community Edition installed

7. I go to the browser and enter the nextcloud settings, I press the save button, it gives an error:
**Error while downloading the document file to be converted.) (версия 7.1.0.215)**

https://github.com/jiriks74/Docker-DocumentServer **( full instruction )**

What could be causing the error, how can it be solved??

**Comment by ShockwaveNN** [comment]
> Error while downloading the document file to be converted.) (версия 7.1.0.215)

This error usually mena that DocumentServer cannot access file it's trying to convert, usually due to network errors

Check `/var/log/onlyoffice/` for any details

**Comment by webagroprom** [comment]
> > Error while downloading the document file to be converted.) (версия 7.1.0.215)
> 
> This error usually mena that DocumentServer cannot access file it's trying to convert, usually due to network errors
> 
> Check `/var/log/onlyoffice/` for any details

**Checked, gives an error**

```
[2022-05-26T16:47:49.213] [ERROR] nodeJS - dnsLookup error: hostname = example.ru
Error: getaddrinfo EAI_AGAIN  example.ru
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26)
[2022-05-26T16:47:49.213] [ERROR] nodeJS - checkIpFilter error:url=https:/example.ru/apps/onlyoffice/empty?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY3Rpb24iOiJlbXB0eSJ9.AOWo1tb7MieSkbPNBZsA_yzAf7qM4MvEvsuT--RHlUo;code:403;(id=conv_check_209251679_docx)
```

How to solve this error?

**Comment by ShockwaveNN** [comment]
This mean that in some of your configs there is host example.ru and DocumentServer thinks that it's store it files there

This host is non-existing and so it fails

Look you configs for `example.ru` - I think it cannot be in our source at all, your attached docker-compose has no mention of it either, but seems that nextcloud is aware of it

**Comment by webagroprom** [comment]
> This mean that in some of your configs there is host example.ru and DocumentServer thinks that it's store it files there
> 
> This host is non-existing and so it fails
> 
> Look you configs for `example.ru` - I think it cannot be in our source at all, your attached docker-compose has no mention of it either, but seems that nextcloud is aware of it

Where exactly are the configs that can be edited to solve the error?

Above I have given all the steps that I do to set up the integration of onlyoffice + nextcloud

In this error, where the example.ru domain is indicated, my domain is shown on which I have nextcloud installed. Example.ru I indicated for an example.

**Comment by ShockwaveNN** [comment]
Ok, got it, understand that example.ru is just a template

```
[2022-05-26T16:47:49.213] [ERROR] nodeJS - dnsLookup error: hostname = example.ru
Error: getaddrinfo EAI_AGAIN  example.ru
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26)
```

This error means that DocumentServer cannot resolve or access the hostname you've used in the config of the Nextcloud connector plugin

Usually, it's some network problem or something like this, especially if you're in Russia (judging by your example URL) some server can be in RKN block list by error

So proper way to check - connect to the DocumentServer container and ping/curl that address from inside of container and if you get any error on ping\curl - that mean that it's not a bug in DocumentServer but issue in your network configuration

**Comment by webagroprom** [comment]
> Ok, got it, understand that example.ru is just a template
> 
> ```
> [2022-05-26T16:47:49.213] [ERROR] nodeJS - dnsLookup error: hostname = example.ru
> Error: getaddrinfo EAI_AGAIN  example.ru
>     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26)
> ```
> 
> This error means that DocumentServer cannot resolve or access the hostname you've used in the config of the Nextcloud connector plugin
> 
> Usually, it's some network problem or something like this, especially if you're in Russia (judging by your example URL) some server can be in RKN block list by error
> 
> So proper way to check - connect to the DocumentServer container and ping/curl that address from inside of container and if you get any error on ping\curl - that mean that it's not a bug in DocumentServer but issue in your network configuration

**curl https://192.168.200.11:9000**

curl: (60) SSL certificate problem: self signed certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

**But if I go to this address in the browser** https://192.168.200.11:9000 (it says that the certificate is not verified), I forcefully accept a non-secure security certificate, the onlyoffice page opens with a greeting:

ONLYOFFICE Docs Community Edition installed
To edit office documents and collaborate, integrate ONLYOFFICE Docs into your sync&share app.

Self-signed security certificate ( openSSL )
I plan to use onlyoffice inside the local network without direct access outside the onlyoffice application

How to bypass certificate verification?
Are there other solutions to this error?

**Comment by ShockwaveNN** [comment]
I think enabling of option [USE_UNAUTHORIZED_STORAGE](https://github.com/ONLYOFFICE/Docker-DocumentServer/#available-configuration-parameters) may help you

Didn't check it for long time through, since clients prefer to use legit certificate in most cases after rise of Let's Encrypt

**Comment by webagroprom** [comment]
> I think enabling of option [USE_UNAUTHORIZED_STORAGE](https://github.com/ONLYOFFICE/Docker-DocumentServer/#available-configuration-parameters) may help you
> 
> Didn't check it for long time through, since clients prefer to use legit certificate in most cases after rise of Let's Encrypt

I plan to use onlyoffice on the local network, so there is no need to connect Let's Encrypt.
What is the correct way to add the USE_UNAUTHORIZED_STORAGE setting to docker-compose ?

```
# Uncomment strings below to enable the JSON Web Token validation.
      - JWT_ENABLED=true
      - JWT_SECRET=123123123
      - JWT_HEADER=AuthorizationJwt
      - JWT_IN_BODY=true
      - USE_UNAUTHORIZED_STORAGE=true
      # Uncomment the line below to set larger file limits (about 1GB)
      #- LARGER_FILE_LIMITS=true
    ports:
      - '9050:80'
      - '9000:443'
    stdin_open: true
    restart: always
    stop_grace_period: 120s
```

Is this addition of a parameter correct?

**Comment by ShockwaveNN** [comment]
Yeah, look ok, but as said not sure if it working right now, since it was somehow related to nodejs version in previous times and something may changed since..

**Comment by toonemastic** [comment]
Hello,

Facing to the same issue running netcloudpi on a raspberry pi using the same docker-compose.
I launch the containers using these commands in a bash script : 
**export DOCKERHOST=$(ifconfig | grep -E "([0-9]{1,3}\.){3}[0-9]{1,3}" | grep -v 127.0.0.1 | awk '{ print $2 }' | cut -f2 -d: | head -n1)
docker-compose up -d**
And add these lines in docker-compose.yml for the service onlyoffice-documentserver:  :
    extra_hosts:
      - "dockerhost:$DOCKERHOST"

I see in the logs/documentserver/converter/out.log this error : 
[2022-05-30T12:07:15.991] [ERROR] nodeJS - error downloadFile:url=https://dockerhost/index.php/apps/onlyoffice/empty?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY3Rpb24iOiJlbXB0eSJ9.ed9EyZ_kJw0pcqBQ1aZ0B_pEkVrRoAzAUlpJ1DTJMzY;attempt=3;code:undefined;connect:undefined;(id=conv_check_450561579_docx)
Error: Error response: statusCode:400; headers:{"date":"Mon, 30 May 2022 12:07:15 GMT","server":"Apache","expires":"Thu, 19 Nov 1981 08:52:00 GMT","cache-control":"no-store, no-cache, must-revalidate","pragma":"no-cache","content-security-policy":"default-src 'self'; script-src 'self' 'nonce-Z2o2VmFzaXlqcWJaK09KYlMxZmpnSTgrRlhTUGlsWXE3R045ZHlhbDg5UT06eEh6TlhwclZ5ZjZva05NMkpEMkl3OE50WkRmSDJpZFpxMU1YTlVIRWdiST0='; style-src 'self' 'unsafe-inline'; frame-src *; img-src * data: blob:; font-src 'self' data:; media-src *; connect-src *; object-src 'none'; base-uri 'self';","set-cookie":["oc_sessionPassphrase=aHaHD4T6Io%2B%2BjZ%2BcuVLcB%2BUCHeW40JqSBdPM0j%2B0q%2By29BUlN62vjnbHG3PRoRuwct0rdqsslalxVC44BVEJ7ODsEmWV2mhhB9Vl6qAN8c%2FZkbpTcsFFeGtOSpdNG3mq; path=/; secure; HttpOnly; SameSite=Lax","ocmh3ubw421p=ffnehu66k3s7bu324pc0jjmt89; path=/; secure; HttpOnly; SameSite=Lax","__Host-nc_sameSiteCookielax=true; path=/; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=lax","__Host-nc_sameSiteCookiestrict=true; path=/; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=strict"],"strict-transport-security":"max-age=15768000; includeSubDomains","referrer-policy":"no-referrer","x-content-type-options":"nosniff","x-download-options":"noopen","x-frame-options":"SAMEORIGIN","x-permitted-cross-domain-policies":"none","x-robots-tag":"none","x-xss-protection":"1; mode=block","upgrade":"h2,h2c","connection":"Upgrade, close","transfer-encoding":"chunked","content-type":"text/html; charset=UTF-8"};
    at Request.fResponse (/snapshot/server/build/server/Common/sources/utils.js)
    at Request.emit (events.js:400:28)
    at Request.onRequestResponse (/snapshot/server/build/server/Common/node_modules/request/request.js:1059:10)
    at ClientRequest.emit (events.js:400:28)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:647:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:127:17)
    at TLSSocket.socketOnData (_http_client.js:515:22)
    at TLSSocket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:293:12)
    at readableAddChunk (internal/streams/readable.js:267:9)
    at TLSSocket.Readable.push (internal/streams/readable.js:206:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)

I just don't know what does that means.

Could someone give me a tip?

Regards,

Pierre

**Comment by webagroprom** [comment]
> Yeah, look ok, but as said not sure if it working right now, since it was somehow related to nodejs version in previous times and something may changed since..

Added to my configuration docker-compose: **USE_UNAUTHORIZED_STORAGE=true**

```
# Uncomment strings below to enable the JSON Web Token validation.
      - JWT_ENABLED=true
      - JWT_SECRET=123123123
      - JWT_HEADER=AuthorizationJwt
      - JWT_IN_BODY=true
      - USE_UNAUTHORIZED_STORAGE=true
      # Uncomment the line below to set larger file limits (about 1GB)
      #- LARGER_FILE_LIMITS=true
    ports:
      - '9050:80'
      - '9000:443'
    stdin_open: true
    restart: always
    stop_grace_period: 120s
```

 **Error while downloading the document file to be converted.) (версия 7.1.0.215)**

**Comment by ShockwaveNN** [comment]
Could you temporary disable jwt and see if problem still persists, maybe this config is broken as I said  (

**Comment by toonemastic** [comment]
jwt disable : same issue

**Comment by webagroprom** [comment]
> Could you temporary disable jwt and see if problem still persists, maybe this config is broken as I said (

**docker-compose.yml** Disable jwt

```
 # Uncomment strings below to enable the JSON Web Token validation.
      # - JWT_ENABLED=true
      # - JWT_SECRET=123123123
      # - JWT_HEADER=AuthorizationJwt
      # - JWT_IN_BODY=true
      # - USE_UNAUTHORIZED_STORAGE=true
      # Uncomment the line below to set larger file limits (about 1GB)
      #- LARGER_FILE_LIMITS=true
    ports:
      - '9050:80'
      - '9000:443'
    stdin_open: true
    restart: always
    stop_grace_period: 120s
    # command: bash -c "/var/www/onlyoffice/documentserver/npm/json -f /etc/onlyoffice/documentserver/default.json -I$

```
**Disable jwt nextcloud** and eject secret key.

**Error while downloading the document file to be converted.) (версия 7.1.0.215)**

**Comment by ShockwaveNN** [comment]
Ok, seems that this option can be broken

We'll look at that as soon as we got free time

**Comment by igwyd** [comment]
hello @webagroprom, first of all, you are using someone else's docker container based on our product ```image: jiriks74/onlyoffice-documentserver:latest``` we won't be able to help with this. Our containers you can get from [docker hub](https://hub.docker.com/r/onlyoffice/documentserver/), and it should be ```image: onlyoffice/documentserver:latest```.
I checked connection onlyoffice and nextcloud with using self signed certs in local network (for examlpe i took your docker-compose.yml and our image onlyoffice/documentserver:latest), its work fine. 

I did everything the same as you in the first post, with a few changes:
you need choose our official docker image **image: onlyoffice/documentserver:latest** and as @ShockwaveNN posted add **USE_UNAUTHORIZED_STORAGE=true** variable for ignore certs check, docker-compose.yml should look like this:
```
version: '2'
services:
  onlyoffice-documentserver:
    image: onlyoffice/documentserver:latest
    container_name: onlyoffice-documentserver
    depends_on:
      - onlyoffice-postgresql
      - onlyoffice-rabbitmq
    environment:
      - DB_TYPE=postgres
      - DB_HOST=onlyoffice-postgresql
      - DB_PORT=5432
      - DB_NAME=onlyoffice
      - DB_USER=onlyoffice
      - AMQP_URI=amqp://guest:guest@onlyoffice-rabbitmq
      - USE_UNAUTHORIZED_STORAGE=true
      # Uncomment strings below to enable the JSON Web Token validation.
      - JWT_ENABLED=true
      - JWT_SECRET=123123123
      - JWT_HEADER=AuthorizationJwt
      - JWT_IN_BODY=true
...
```
The nextcloud also has a certificate check, do not forget to disable it when setting up:
![NC](https://user-images.githubusercontent.com/67538082/171196333-bbc272bd-97a7-46be-bbab-ec4d10d141e2.jpg)

PS We have official documentation how Installing ONLYOFFICE Docs with docker [here](https://helpcenter.onlyoffice.com/installation/docs-community-install-docker.aspx).
