### ISSUE TITLE
Image onlyoffice ARM64 shows error and does not go up

### ISSUE THREAD

**Issue by talesam** [ONLYOFFICE/Docker-DocumentServer#474]
Now the image is out for ARM64, but it's giving an error when uploading, on x86 it works fine.

I'm running on an Oracle ARM64 server.

### Here is doker-compose.yml:
```
version: '3.9'

services:
  onlyoffice:
    container_name: onlyoffice
    image: onlyoffice/documentserver:latest
    #restart: always
    volumes:
      - /home/tales/Docker/OnlyOffice/data:/var/www/onlyoffice/Data:rw
      - /home/tales/Docker/OnlyOffice/logs:/var/log/onlyoffice
    expose:
      - 80
      - 443
    networks:
      t4l35-net:

networks:
  t4l35-net:
    name: t4l35-net
```

### And here is the error that appears in the log:
```
exec /app/ds/run-document-server.sh: exec format error
```
