### ISSUE TITLE
Can't Access from HTTPS

### ISSUE THREAD

**Issue by juliettebee** [ONLYOFFICE/Docker-DocumentServer#620]
Hello, when I try to access OnlyOffice I'm unable to connect. My Docker-Compose is:
```yaml
---
version: "2.1"
services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    ports:
      - 443:443
    volumes:
      - ./conf:/config
      - ./syncthing:/data
      - ./keys:/keys 
    restart: unless-stopped
    links:
      - db
  db:
    image: postgres 
    restart: always
    environment:
      POSTGRES_PASSWORD: <strong password>
      POSTGRES_USER: nextcloud
    volumes:
      - ./nextclouddb:/var/lib/postgresql/data
  onlyoffice-document-server: 
    image: onlyoffice/documentserver:latest
    restart: always
    environment:
      - JWT_SECRET=secret 
    ports:
      - 9980:443
    expose:
      - 443
    volumes:
      - ./keys:/app/onlyoffice/DocumentServer/data/
 ```
I'm able to access OnlyOffice when I have it set up with port 80, but I need to have it be on port 443. And my host OS is Ubuntu 22.04. Is there a way to fix this?
