### ISSUE TITLE
Onlyofficedocs need long time to start because the inner rabbitmq some time not start

### ISSUE THREAD

**Issue by chendelin1982** [ONLYOFFICE/Docker-DocumentServer#699]
**Do you want to request a *feature* or report a *bug*?**

When use Onlyofficedocs, I found it need long time to start because the **inner rabbitmq** some time not start. logs below
```
Waiting for connection to the localhost host on port 5672
```

If I add outside rabbitmq, Onlyofficedocs starting very quickly
```
version: '3.8'
services:     
  onlyofficedocs:
    container_name: ${W9_ID}
    image: ${W9_REPO}:${W9_VERSION}
    restart: unless-stopped
    env_file:
      - .env
    cpus: 0.5
    ports:
      - ${W9_HTTP_PORT_SET}:80
    expose:
      - '80'
      - '443'
    environment:
      - AMQP_URI=amqp://guest:guest@${W9_ID}-rabbitmq
    volumes:
      - data:/var/www/onlyoffice/Data
      - log:/var/log/onlyoffice
      - db:/var/lib/postgresql
      - lib:/var/lib/onlyoffice
      - cache:/var/lib/redis
      - mq:/var/lib/rabbitmq
      - fonts:/usr/share/fonts/truetype/custom
      - forgotten:/var/lib/onlyoffice/documentserver/App_Data/cache/files/forgotten

  rabbitmq:
    container_name: ${W9_ID}-rabbitmq
    image: rabbitmq
    restart: unless-stopped
    expose:
      - '5672'

networks:
  default:
    name: ${W9_NETWORK}
    external: true

volumes:
  data:
  log:
  db:
  lib:
  cache:
  mq:
  fonts:
  forgotten:

```
