### ISSUE TITLE
How to use docker for 

### ISSUE THREAD

**Issue by 1n5aN1aC** [ONLYOFFICE/Docker-DocumentServer#784]
Not exactly a bug, but probably a lack of understanding, and unable to find direction in the documentation.

I wished to start with something very similar to the built-in example, (ds:example) so I started the docker container using docker-compose:
```
  onlyoffice:
    container_name: onlyoffice
    image: onlyoffice/documentserver
    restart: always
    ports:
      - "1005:80"
    environment:
      JWT_SECRET: example_jwt_secret
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/onlyoffice/files:/var/lib/onlyoffice
      - /docker/onlyoffice/db:/var/lib/postgresql
      - /docker/onlyoffice/fonts:/usr/share/fonts
```

And I can successfully access the web interface, and I saw the instructions to start the examples:
`sudo docker exec 03610350a9a6 sudo supervisorctl start ds:example`
or
`sudo docker exec 03610350a9a6 sudo sed 's,autostart=false,autostart=true,' -i /etc/supervisor/conf.d/ds-example.conf`

I run those commands and they work.  So from that example, I assume the correct way to create my own services is to create my own file with my own content in that directory.

However, the biggest thing I do not understand is how to make that service run permanently.  As an example, lets say I just want to use the example permanently.  (Only as an example)  
-  I cannot simple do as the example says, as that will be lost upon upgrading the container.  
-  I tried mapping the /etc/supervisor/conf.d folder to a local folder, putting my examples in it, and setting autostart=true.  Upon restarting the container, nothing happened, and the logs seem to indicate it found no services to start.  Even though I confirmed the files are in the correct location inside the container.

So what is the intended way to actually use this container?

Thanks!!

**Host Operating System:**
Linux EXAMPLE 6.11.10-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.11.10-1 (2024-11-23) x86_64 GNU/Linux
Docker version 26.1.5+dfsg1, build a72d7cd
