### ISSUE TITLE
Problem with make docker https

### ISSUE THREAD

**Issue by mdonadel83** [ONLYOFFICE/Docker-DocumentServer#804]
I use Ubuntu version 24.10 without GUI. So i installed [docker.io](http://docker.io/) and docker-compose with apt , i downloaded the project from here (git for docker-documentserver), i used the docker-compose.yml and i want to make it works with https .I only added to the yml you find here this strings:

>   - LETS_ENCRYPT_DOMAIN=xx.xx.it
>   - LETS_ENCRYPT_MAIL=xx.xx@xx.com

and i added also this:
 
>  - USE_UNAUTHORIZED_STORAGE=true

so the docker-compose now is:

```
services:
  onlyoffice-documentserver:
    build:
      context: .
    container_name: onlyoffice-documentserver
    depends_on:
      - onlyoffice-postgresql
      - onlyoffice-rabbitmq
    environment:
      - DB_TYPE=postgres
      - DB_HOST=onlyoffice-postgresql
      - DB_PORT=5432
      - DB_NAME=onlyoffice
      - DB_USER=onlyoffice
      - AMQP_URI=amqp://guest:guest@onlyoffice-rabbitmq
      - LETS_ENCRYPT_DOMAIN=xx.xx.it
      - LETS_ENCRYPT_MAIL=xx.xx@xx.com
      - USE_UNAUTHORIZED_STORAGE=true
      # Uncomment strings below to enable the JSON Web Token validation.
      - JWT_ENABLED=true
      - JWT_SECRET=6p9J7JzyCabipsYb4EIorDk89EhWCCEv
      - JWT_HEADER=AuthorizationJwt
      - JWT_IN_BODY=true
    ports:
      - '80:80'
      - '443:443'
    stdin_open: true
    restart: always
    stop_grace_period: 60s
    volumes:
       - /var/www/onlyoffice/Data
       - /var/log/onlyoffice
       - /var/lib/onlyoffice/documentserver/App_Data/cache/files
       - /var/www/onlyoffice/documentserver-example/public/files
       - /usr/share/fonts

  onlyoffice-rabbitmq:
    container_name: onlyoffice-rabbitmq
    image: rabbitmq
    restart: always
    expose:
      - '5672'

  onlyoffice-postgresql:
    container_name: onlyoffice-postgresql
    image: postgres:12
    environment:
      - POSTGRES_DB=onlyoffice
      - POSTGRES_USER=onlyoffice
      - POSTGRES_HOST_AUTH_METHOD=trust
    restart: always
    expose:
      - '5432'
    volumes:
      - postgresql_data:/var/lib/postgresql

volumes:
  postgresql_data:
```

Into onlyoffice server i configure the /etc/hosts , into this i add the IP number of the server and the name of the site is delared into letscrypt domain.
i started the docker with

docker-compose -d

The ssl works cause a connection from outside into the site i have dedicated for onlyoffice server it's ok.
After, i like try to test the server with the command i have in the site page , so into a machine i started the example with:

> sudo docker exec 4618f69e73bd sudo supervisorctl start ds:example

it respond with:

> ds:example: started

so i go to the site in https://xxx.xxxx.it/example and all works cause i see the “ONLYOFFICE Document Editors – Welcome!”

but when i try to click, for example Document i have this problem :

![Image](https://github.com/user-attachments/assets/05e1e3a7-7c2e-4743-93ec-7ec6efe701a9)

from docker i have this message:

```
onlyoffice-documentserver    | ds:converter: stopped
onlyoffice-documentserver    | ds:converter: started
onlyoffice-documentserver    |  * Reloading nginx configuration nginx
onlyoffice-documentserver    |    ...done.
onlyoffice-documentserver    | Installing plugins, please wait...Done
onlyoffice-documentserver    |  * Reloading nginx configuration nginx
onlyoffice-documentserver    |    ...done.
onlyoffice-documentserver    |
onlyoffice-documentserver    | ==> /var/log/onlyoffice/documentserver/converter/err.log <==
onlyoffice-documentserver    |
onlyoffice-documentserver    | ==> /var/log/onlyoffice/documentserver/converter/out.log <==
onlyoffice-documentserver    |     at Request.onRequestResponse (/snapshot/server/Common/node_modules/request/request.js:1066:10)
onlyoffice-documentserver    |     at ClientRequest.emit (node:events:527:28)
onlyoffice-documentserver    |     at HTTPParser.parserOnIncomingClient (node:_http_client:631:27)
onlyoffice-documentserver    |     at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
onlyoffice-documentserver    |     at TLSSocket.socketOnData (node:_http_client:494:22)
onlyoffice-documentserver    |     at TLSSocket.emit (node:events:527:28)
onlyoffice-documentserver    |     at addChunk (node:internal/streams/readable:315:12)
onlyoffice-documentserver    |     at readableAddChunk (node:internal/streams/readable:289:9)
onlyoffice-documentserver    |     at TLSSocket.Readable.push (node:internal/streams/readable:228:10)
onlyoffice-documentserver    |     at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)
onlyoffice-documentserver    |
onlyoffice-documentserver    | ==> /var/log/onlyoffice/documentserver/docservice/err.log <==
onlyoffice-documentserver    |
onlyoffice-documentserver    | ==> /var/log/onlyoffice/documentserver/docservice/out.log <==
onlyoffice-documentserver    | [2025-03-31T21:02:59.587] [WARN] [localhost] [docId] [userId] nodeJS - Express server starting...
onlyoffice-documentserver    | [2025-03-31T21:02:59.591] [WARN] [localhost] [docId] [userId] nodeJS - notifyLicenseExpiration(): expiration date is not defined
onlyoffice-documentserver    | [2025-03-31T21:02:59.592] [WARN] [localhost] [docId] [userId] nodeJS - notifyLicenseExpiration(): expiration date is not defined
onlyoffice-documentserver    | [2025-03-31T21:02:59.747] [WARN] [localhost] [docId] [userId] nodeJS - Express server listening on port 8000 in production-linux mode. Version: 8.3.2. Build: 19
onlyoffice-documentserver    | [2025-03-31T21:03:34.571] [WARN] [localhost] [docId] [userId] nodeJS - Express server starting...
onlyoffice-documentserver    | [2025-03-31T21:03:34.575] [WARN] [localhost] [docId] [userId] nodeJS - notifyLicenseExpiration(): expiration date is not defined
onlyoffice-documentserver    | [2025-03-31T21:03:34.575] [WARN] [localhost] [docId] [userId] nodeJS - notifyLicenseExpiration(): expiration date is not defined
onlyoffice-documentserver    | [2025-03-31T21:03:34.690] [WARN] [localhost] [docId] [userId] nodeJS - Express server listening on port 8000 in production-linux mode. Version: 8.3.2. Build: 19
onlyoffice-documentserver    |
onlyoffice-documentserver    | ==> /var/log/onlyoffice/documentserver/nginx.error.log <==
onlyoffice-documentserver    | 2025/03/31 21:04:27 [error] 960#960: *27 connect() failed (111: Connection refused) while connecting to upstream, client: 151.38.59.91, server: , request: "GET /example/ HTTP/2.0", upstream: "http://127.0.0.1:3000/", host: "xxx.xxxx.it", referrer: "https://xxx.xxx.it/welcome/"
onlyoffice-documentserver    | 2025/03/31 21:04:27 [error] 960#960: *27 connect() failed (111: Connection refused) while connecting to upstream, client: 151.38.59.91, server: , request: "GET /example/ HTTP/2.0", upstream: "http://127.0.0.1:3000/", host: "xxx.xxx.it", referrer: "https://xxx.xxx.it/welcome/"
onlyoffice-documentserver    |
onlyoffice-documentserver    | ==> /var/log/onlyoffice/documentserver/docservice/out.log <==
onlyoffice-documentserver    | [2025-03-31T21:05:32.721] [ERROR] [localhost] [151.38.59.91new.docx1743455131407] [uid-1] nodeJS - postData error: url = https://xxx.xxx.it/example/track?filename=new.docx&useraddress=151.38.59.91;data = {"key":"151.38.59.91new.docx1743455131407","status":1,"users":["uid-1"],"actions":[{"type":1,"userid":"uid-1"}],"token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJrZXkiOiIxNTEuMzguNTkuOTFuZXcuZG9jeDE3NDM0NTUxMzE0MDciLCJzdGF0dXMiOjEsInVzZXJzIjpbInVpZC0xIl0sImFjdGlvbnMiOlt7InR5cGUiOjEsInVzZXJpZCI6InVpZC0xIn1dLCJpYXQiOjE3NDM0NTUxMzIsImV4cCI6MTc0MzQ1NTQzMn0.qNlaAKF_hJCDV7R8Eza6zvXXT5FP_X3GbliRnNzCifs"} Error: Error response: statusCode:404; headers:{"server":"nginx","date":"Mon, 31 Mar 2025 21:05:32 GMT","content-type":"text/html","transfer-encoding":"chunked","connection":"keep-alive","content-encoding":"gzip"}; body:
onlyoffice-documentserver    | <html>
onlyoffice-documentserver    | <head><title>404 Not Found</title></head>
onlyoffice-documentserver    | <body>
onlyoffice-documentserver    | <center><h1>404 Not Found</h1></center>
onlyoffice-documentserver    | <hr><center>nginx</center>
onlyoffice-documentserver    | </body>
onlyoffice-documentserver    | </html>
onlyoffice-documentserver    |
onlyoffice-documentserver    |     at Request._callback (/snapshot/server/Common/sources/utils.js)
onlyoffice-documentserver    |     at Request.callback (/snapshot/server/Common/node_modules/request/request.js:185:22)
onlyoffice-documentserver    |     at Request.emit (node:events:527:28)
onlyoffice-documentserver    |     at Request.<anonymous> (/snapshot/server/Common/node_modules/request/request.js:1161:10)
onlyoffice-documentserver    |     at Request.emit (node:events:527:28)
onlyoffice-documentserver    |     at Gunzip.<anonymous> (/snapshot/server/Common/node_modules/request/request.js:1083:12)
onlyoffice-documentserver    |     at Object.onceWrapper (node:events:641:28)
onlyoffice-documentserver    |     at Gunzip.emit (node:events:527:28)
onlyoffice-documentserver    |     at endReadableNT (node:internal/streams/readable:1345:12)
onlyoffice-documentserver    |     at processTicksAndRejections (node:internal/process/task_queues:83:21)
onlyoffice-documentserver    | ==> /var/log/onlyoffice/documentserver/converter/out.log <==
onlyoffice-documentserver    | [2025-03-31T21:05:32.723] [ERROR] [localhost] [151.38.59.91new.docx1743455131407] [uid-1] nodeJS - error downloadFile:url=https://xxx.xxx.it/example/download?fileName=new.docx&useraddress=151.38.59.91;attempt=1;code:null;connect:null Error: Error response: statusCode:404; headers:{"server":"nginx","date":"Mon, 31 Mar 2025 21:05:32 GMT","content-type":"text/html","transfer-encoding":"chunked","connection":"keep-alive","content-encoding":"gzip"};
onlyoffice-documentserver    |     at Request.fResponse (/snapshot/server/Common/sources/utils.js)
onlyoffice-documentserver    |     at Request.emit (node:events:527:28)
onlyoffice-documentserver    |     at Request.onRequestResponse (/snapshot/server/Common/node_modules/request/request.js:1066:10)
onlyoffice-documentserver    |     at ClientRequest.emit (node:events:527:28)
onlyoffice-documentserver    |     at HTTPParser.parserOnIncomingClient (node:_http_client:631:27)
onlyoffice-documentserver    |     at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
onlyoffice-documentserver    |     at TLSSocket.socketOnData (node:_http_client:494:22)
onlyoffice-documentserver    |     at TLSSocket.emit (node:events:527:28)
onlyoffice-documentserver    |     at addChunk (node:internal/streams/readable:315:12)
onlyoffice-documentserver    |     at readableAddChunk (node:internal/streams/readable:289:9)
onlyoffice-documentserver    |     at TLSSocket.Readable.push (node:internal/streams/readable:228:10)
onlyoffice-documentserver    |     at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)

```
