### ISSUE TITLE
Issue with latest rabbimq image 4.1.0+

### ISSUE THREAD

**Issue by le-zell** [ONLYOFFICE/Docker-DocumentServer#805]
Hello when we are pulling our docker-compose (with latest rabbitmq image 4.1.0+), 

we have errors like explained here : 

https://github.com/rabbitmq/rabbitmq-server/discussions/13616

due to breaking changes explained here : https://github.com/rabbitmq/rabbitmq-server/blob/main/release-notes/4.1.0.md#initial-amqp-0-9-1-maximum-frame-size

The document server does not work at all.

Tried with onlyoffice/documentserver-ee:8.3.3 and onlyoffice/documentserver-ee:8.3.2 images.

only workaround fix that i found rabbitmq image to 4.0.9 version like : 

```
onlyoffice-rabbitmq:
    container_name: onlyoffice-rabbitmq
    image: rabbitmq:4.0.9
    restart: always
    expose:
      - '5672'
```

docker compose pull / down / up => it's working.
