### ISSUE TITLE
Healthcheck not working 502 Error

### ISSUE THREAD

**Issue by Semarnat73** [ONLYOFFICE/Docker-DocumentServer#811]
Hello, I have my small server, and when I update it, the Docker packages are the ones causing the errors. Before updating these packages, everything works without any issues. After updating, the container stops working.

```
root@mail:~# dpkg -l {docker-buildx-plugin,docker-ce-cli,docker-ce-rootless-extras,docker-ce,docker-compose-plugin,libperl5.36,linux-image-amd64,linux-libc-dev,perl-base,perl-modules-5.36,perl}
Deseado=desconocido(U)/Instalar/eliminaR/Purgar/retener(H)
| Estado=No/Inst/ficheros-Conf/desempaqUetado/medio-conF/medio-inst(H)/espera-disparo(W)/pendienTe-disparo
|/ Err?=(ninguno)/requiere-Reinst (Estado,Err: mayúsc.=malo)
||/ Nombre                    Versión                       Arquitectura Descripción
+++-=========================-=============================-============-========================================================
ii  docker-buildx-plugin      0.22.0-1~debian.12~bookworm   amd64        Docker Buildx cli plugin.
ii  docker-ce                 5:28.0.4-1~debian.12~bookworm amd64        Docker: the open-source application container engine
ii  docker-ce-cli             5:28.0.4-1~debian.12~bookworm amd64        Docker CLI: the open-source application container engine
ii  docker-ce-rootless-extras 5:28.0.4-1~debian.12~bookworm amd64        Rootless support for Docker.
ii  docker-compose-plugin     2.34.0-1~debian.12~bookworm   amd64        Docker Compose (V2) plugin for the Docker CLI.
ii  libperl5.36:amd64         5.36.0-7+deb12u1              amd64        shared Perl library
ii  linux-image-amd64         6.1.129-1                     amd64        Linux for 64-bit PCs (meta-package)
ii  linux-libc-dev:amd64      6.1.129-1                     amd64        Linux support headers for userspace development
ii  perl                      5.36.0-7+deb12u1              amd64        Larry Wall's Practical Extraction and Report Language
ii  perl-base                 5.36.0-7+deb12u1              amd64        minimal Perl system
ii  perl-modules-5.36         5.36.0-7+deb12u1              all          Core Perl modules
root@mail:~# apt list --upgradable
Listando... Hecho
docker-buildx-plugin/bookworm 0.23.0-1~debian.12~bookworm amd64 [actualizable desde: 0.22.0-1~debian.12~bookworm]
docker-ce-cli/bookworm 5:28.1.1-1~debian.12~bookworm amd64 [actualizable desde: 5:28.0.4-1~debian.12~bookworm]
docker-ce-rootless-extras/bookworm 5:28.1.1-1~debian.12~bookworm amd64 [actualizable desde: 5:28.0.4-1~debian.12~bookworm]
docker-ce/bookworm 5:28.1.1-1~debian.12~bookworm amd64 [actualizable desde: 5:28.0.4-1~debian.12~bookworm]
docker-compose-plugin/bookworm 2.35.1-1~debian.12~bookworm amd64 [actualizable desde: 2.34.0-1~debian.12~bookworm]
libperl5.36/stable-security 5.36.0-7+deb12u2 amd64 [actualizable desde: 5.36.0-7+deb12u1]
linux-image-amd64/stable-security 6.1.135-1 amd64 [actualizable desde: 6.1.129-1]
linux-libc-dev/stable-security 6.1.135-1 amd64 [actualizable desde: 6.1.129-1]
perl-base/stable-security 5.36.0-7+deb12u2 amd64 [actualizable desde: 5.36.0-7+deb12u1]
perl-modules-5.36/stable-security 5.36.0-7+deb12u2 all [actualizable desde: 5.36.0-7+deb12u1]
perl/stable-security 5.36.0-7+deb12u2 amd64 [actualizable desde: 5.36.0-7+deb12u1]
```
Up to the kernel versions linux-image-6.1.0-32-amd64 and linux-image-6.1.0-34-amd64, everything works correctly as long as the Docker packages are not updated. The healthcheck fails — the new Docker packages break the container's functionality.

>  [!TIP]
> Do not update the Docker packages, or downgrade them to restore proper container behavior.

**Comment by igwyd** [comment]
Hello @Semarnat73, please show the error you get when run container and show the command how you running documentserver.

**Comment by Semarnat73** [comment]
In my case, the first problem—the first error—came from onlyoffice-documentserver.

```
==> /var/log/onlyoffice/documentserver/docservice/out.log <==
[2025-05-20T02:40:58.330] [ERROR] [localhost] [docId] [userId] nodeJS - [AMQP] Error: connect ECONNREFUSED 127.0.0.1:5672
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)

==> /var/log/onlyoffice/documentserver/converter/out.log <==
[2025-05-20T02:40:59.222] [ERROR] [localhost] [docId] [userId] nodeJS - [AMQP] Error: connect ECONNREFUSED 127.0.0.1:5672
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
```

The solution was to add an explicit private network; it's possible that some other service had port conflicts.
Then, the next error was with onlyoffice-rabbitmq.

```
2025-05-20T02:59:01.118423+00:00 error: FORMATTER CRASH: {"closing AMQP connection ~tp (~ts):~nfailed to negotiate connection parameters: ~ts",[<0.780.0>,<<"172.22.0.4:37934 -> 172.22.0.2:5672">>,"3s","negotiated frame_max = 4096 is lower than the minimum allowed value (8192)"]}
2025-05-20T02:59:02.027423+00:00 error: FORMATTER CRASH: {"closing AMQP connection ~tp (~ts):~nfailed to negotiate connection parameters: ~ts",[<0.784.0>,<<"172.22.0.4:37940 -> 172.22.0.2:5672">>,"3s","negotiated frame_max = 4096 is lower than the minimum allowed value (8192)"]}
```

The solution was to use the latest 3.13.x version, since 4.1.x...

[https://github.com/rabbitmq/rabbitmq-server/blob/main/release-notes/4.1.0.md#initial-amqp-0-9-1-maximum-frame-size](url)
Initial AMQP 0-9-1 Maximum Frame Size

Before a client connection can negotiate a maximum frame size (frame_max), it must authenticate successfully. Before the authenticated phase, a special lower frame_max value is used.

With this release, the value was increased from the original 4096 bytes to 8192 to accommodate larger JWT tokens.

My solution was to use version 3.13.7.

```
services:
  onlyoffice-documentserver:
    image: onlyoffice/documentserver:latest
    container_name: onlyoffice-documentserver
    depends_on:
      - onlyoffice-postgresql
      - onlyoffice-rabbitmq
    environment:
      - DB_TYPE=postgres
      - DB_HOST=onlyoffice-postgresql
      - DB_PORT=5432
      - DB_NAME=onlyoffice
      - DB_USER=onlyoffice
      - AMQP_URI=amqp://guest:guest@onlyoffice-rabbitmq
      # Uncomment strings below to enable the JSON Web Token validation.
      - JWT_ENABLED=true
      - JWT_SECRET=passwd
      - JWT_HEADER=Authorization
      - JWT_IN_BODY=true
    ports:
      - '801:80'
      - '4431:443'
    stdin_open: true
    restart: unless-stopped
    tty: true
    stop_grace_period: 60s
    volumes:
      - ./onlyoffice/Docs/logs:/var/log/onlyoffice
      - ./onlyoffice/Docs/data:/var/www/onlyoffice/Data
      - ./onlyoffice/Docs/lib:/var/lib/onlyoffice
      - ./onlyoffice/Docs/db:/var/lib/postgresql
    networks:
      - onlyoffice-net

  onlyoffice-rabbitmq:
    container_name: onlyoffice-rabbitmq
    image: rabbitmq:3.13.7
    restart: always
    expose:
      - '5672'
    networks:
      - onlyoffice-net

  onlyoffice-postgresql:
    container_name: onlyoffice-postgresql
    image: postgres:12
    environment:
      - POSTGRES_DB=onlyoffice
      - POSTGRES_USER=onlyoffice
      - POSTGRES_HOST_AUTH_METHOD=trust
    restart: always
    expose:
      - '5432'
    volumes:
      - postgresql_data:/var/lib/postgresql
    networks:
      - onlyoffice-net


volumes:
  postgresql_data:
networks:
  onlyoffice-net:
    driver: bridge
```
